Event.create!([
  {name: "Slipknot", description: "<div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque fringilla lacinia metus, eu egestas sem venenatis vel. Nullam maximus ultricies lacus, sed suscipit lorem feugiat eu. Nunc vel vehicula quam, id sagittis eros. Quisque congue eros velit, ut cursus turpis congue sed. Sed et lacinia libero, non auctor libero. Sed eget mauris malesuada, cursus justo sit amet, cursus velit. Nulla tincidunt fermentum libero, vel vehicula ipsum hendrerit at. Morbi congue odio sed ex imperdiet consectetur. Integer sit amet massa ut ipsum condimentum pulvinar. Donec iaculis eget turpis at pharetra. Maecenas in placerat ex. Suspendisse potent</div>", start_t: "2019-09-13 01:00:00", end_t: "2019-09-13 07:00:00", user_id: 1, seller_id: 1, headline: "Spit It Out", video: "", address_id: 2, features: nil, invite_text: nil, fb_pixel: nil, ga_id: nil},
  {name: "Baile do Nego Véio", description: "<div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque fringilla lacinia metus, eu egestas sem venenatis vel. Nullam maximus ultricies lacus, sed suscipit lorem feugiat eu. Nunc vel vehicula quam, id sagittis eros. Quisque congue eros velit, ut cursus turpis congue sed. Sed et lacinia libero, non auctor libero. Sed eget mauris malesuada, cursus justo sit amet, cursus velit. Nulla tincidunt fermentum libero, vel vehicula ipsum hendrerit at. Morbi congue odio sed ex imperdiet consectetur. Integer sit amet massa ut ipsum condimentum pulvinar. Donec iaculis eget turpis at pharetra. Maecenas in placerat ex. Suspendisse potent</div>", start_t: "2019-09-10 00:00:00", end_t: nil, user_id: 1, seller_id: 1, headline: "Olha quem chegou!", video: "", address_id: 6, features: nil, invite_text: nil, fb_pixel: nil, ga_id: nil},
  {name: "Kendrick Lamar", description: "<div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque fringilla lacinia metus, eu egestas sem venenatis vel. Nullam maximus ultricies lacus, sed suscipit lorem feugiat eu. Nunc vel vehicula quam, id sagittis eros. Quisque congue eros velit, ut cursus turpis congue sed. Sed et lacinia libero, non auctor libero. Sed eget mauris malesuada, cursus justo sit amet, cursus velit. Nulla tincidunt fermentum libero, vel vehicula ipsum hendrerit at. Morbi congue odio sed ex imperdiet consectetur. Integer sit amet massa ut ipsum condimentum pulvinar. Donec iaculis eget turpis at pharetra. Maecenas in placerat ex. Suspendisse potent</div>", start_t: "2019-09-03 23:00:00", end_t: "2019-09-04 06:00:00", user_id: 1, seller_id: 1, headline: "Money Trees Baby!", video: "", address_id: 3, features: nil, invite_text: nil, fb_pixel: nil, ga_id: nil},
  {name: "Anitta", description: "<div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque fringilla lacinia metus, eu egestas sem venenatis vel. Nullam maximus ultricies lacus, sed suscipit lorem feugiat eu. Nunc vel vehicula quam, id sagittis eros. Quisque congue eros velit, ut cursus turpis congue sed. Sed et lacinia libero, non auctor libero. Sed eget mauris malesuada, cursus justo sit amet, cursus velit. Nulla tincidunt fermentum libero, vel vehicula ipsum hendrerit at. Morbi congue odio sed ex imperdiet consectetur. Integer sit amet massa ut ipsum condimentum pulvinar. Donec iaculis eget turpis at pharetra. Maecenas in placerat ex. Suspendisse potent</div>", start_t: "2019-12-10 23:00:00", end_t: nil, user_id: 1, seller_id: 1, headline: "A rainha do funk", video: "", address_id: 4, features: nil, invite_text: nil, fb_pixel: nil, ga_id: nil},
  {name: "Raimundos", description: "<div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque fringilla lacinia metus, eu egestas sem venenatis vel. Nullam maximus ultricies lacus, sed suscipit lorem feugiat eu. Nunc vel vehicula quam, id sagittis eros. Quisque congue eros velit, ut cursus turpis congue sed. Sed et lacinia libero, non auctor libero. Sed eget mauris malesuada, cursus justo sit amet, cursus velit. Nulla tincidunt fermentum libero, vel vehicula ipsum hendrerit at. Morbi congue odio sed ex imperdiet consectetur. Integer sit amet massa ut ipsum condimentum pulvinar. Donec iaculis eget turpis at pharetra. Maecenas in placerat ex. Suspendisse potent</div>", start_t: "2019-11-02 01:00:00", end_t: "2019-11-02 06:00:00", user_id: 1, seller_id: 1, headline: "Venha curtir essa banda lendária!", video: "", address_id: 5, features: nil, invite_text: nil, fb_pixel: nil, ga_id: nil},
  {name: "Zé Ramalho", description: "<div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque fringilla lacinia metus, eu egestas sem venenatis vel. Nullam maximus ultricies lacus, sed suscipit lorem feugiat eu. Nunc vel vehicula quam, id sagittis eros. Quisque congue eros velit, ut cursus turpis congue sed. Sed et lacinia libero, non auctor libero. Sed eget mauris malesuada, cursus justo sit amet, cursus velit. Nulla tincidunt fermentum libero, vel vehicula ipsum hendrerit at. Morbi congue odio sed ex imperdiet consectetur. Integer sit amet massa ut ipsum condimentum pulvinar. Donec iaculis eget turpis at pharetra. Maecenas in placerat ex. Suspendisse potent</div>", start_t: "2019-09-22 01:00:00", end_t: nil, user_id: 1, seller_id: 1, headline: "Chão de Chiz", video: "", address_id: 7, features: nil, invite_text: nil, fb_pixel: nil, ga_id: nil},
  {name: "John Mayer", description: "<div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque fringilla lacinia metus, eu egestas sem venenatis vel. Nullam maximus ultricies lacus, sed suscipit lorem feugiat eu. Nunc vel vehicula quam, id sagittis eros. Quisque congue eros velit, ut cursus turpis congue sed. Sed et lacinia libero, non auctor libero. Sed eget mauris malesuada, cursus justo sit amet, cursus velit. Nulla tincidunt fermentum libero, vel vehicula ipsum hendrerit at. Morbi congue odio sed ex imperdiet consectetur. Integer sit amet massa ut ipsum condimentum pulvinar. Donec iaculis eget turpis at pharetra. Maecenas in placerat ex. Suspendisse potent</div>", start_t: "2019-10-08 01:30:00", end_t: nil, user_id: 1, seller_id: 1, headline: "New Light", video: "", address_id: 8, features: nil, invite_text: nil, fb_pixel: nil, ga_id: nil},
  {name: "Baile da Gaiola", description: "<div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque fringilla lacinia metus, eu egestas sem venenatis vel. Nullam maximus ultricies lacus, sed suscipit lorem feugiat eu. Nunc vel vehicula quam, id sagittis eros. Quisque congue eros velit, ut cursus turpis congue sed. Sed et lacinia libero, non auctor libero. Sed eget mauris malesuada, cursus justo sit amet, cursus velit. Nulla tincidunt fermentum libero, vel vehicula ipsum hendrerit at. Morbi congue odio sed ex imperdiet consectetur. Integer sit amet massa ut ipsum condimentum pulvinar. Donec iaculis eget turpis at pharetra. Maecenas in placerat ex. Suspendisse potent</div>", start_t: "2019-10-20 02:30:00", end_t: "2019-10-20 08:00:00", user_id: 1, seller_id: 1, headline: "Vaaaaaai", video: "", address_id: 9, features: nil, invite_text: nil, fb_pixel: nil, ga_id: nil},
  {name: "Vintage Culture", description: "<div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque fringilla lacinia metus, eu egestas sem venenatis vel. Nullam maximus ultricies lacus, sed suscipit lorem feugiat eu. Nunc vel vehicula quam, id sagittis eros. Quisque congue eros velit, ut cursus turpis congue sed. Sed et lacinia libero, non auctor libero. Sed eget mauris malesuada, cursus justo sit amet, cursus velit. Nulla tincidunt fermentum libero, vel vehicula ipsum hendrerit at. Morbi congue odio sed ex imperdiet consectetur. Integer sit amet massa ut ipsum condimentum pulvinar. Donec iaculis eget turpis at pharetra. Maecenas in placerat ex. Suspendisse potent</div>", start_t: "2019-09-30 01:00:00", end_t: nil, user_id: 1, seller_id: 1, headline: "O melhor DJ do Brasil!", video: "", address_id: 10, features: nil, invite_text: nil, fb_pixel: nil, ga_id: nil}
])
Offer.create!([
  {name: "Entrada Inteira", description: "", event_id: 1, quantity: 100, start_t: "2019-09-04 03:00:00", end_t: "2019-09-13 00:00:00", price_cents: 20000, allotment: 1, sold: 0, active: true},
  {name: "Entrada Meia", description: "", event_id: 1, quantity: 100, start_t: "2019-09-04 03:00:00", end_t: "2019-09-13 00:00:00", price_cents: 10000, allotment: 1, sold: 0, active: true},
  {name: "Entrada VIP", description: "<div><!--block--><strong>Área Exclusiva</strong><br>Open Bar &amp; Open Food<br>Tudo incluso!</div>", event_id: 1, quantity: 50, start_t: "2019-09-04 03:00:00", end_t: "2019-09-11 02:59:00", price_cents: 50000, allotment: 1, sold: 0, active: true},
  {name: "Entrada Inteira", description: "", event_id: 2, quantity: 300, start_t: "2019-08-10 03:00:00", end_t: "2019-09-03 20:00:00", price_cents: 38000, allotment: 1, sold: 0, active: true},
  {name: "Meia Entrada", description: "", event_id: 2, quantity: 600, start_t: "2019-08-15 03:00:00", end_t: "2019-09-02 18:00:00", price_cents: 19000, allotment: 1, sold: 0, active: true},
  {name: "Entrada Inteira", description: "", event_id: 3, quantity: 500, start_t: "2019-09-01 03:00:00", end_t: "2019-12-10 18:00:00", price_cents: 12000, allotment: 1, sold: 0, active: true},
  {name: "Meia Entrada", description: "", event_id: 3, quantity: 90, start_t: "2019-09-01 03:00:00", end_t: "2019-12-10 15:00:00", price_cents: 6000, allotment: 1, sold: 0, active: true},
  {name: "Ingresso Único", description: "", event_id: 4, quantity: 500, start_t: "2019-09-01 03:00:00", end_t: "2019-11-01 21:00:00", price_cents: 5000, allotment: 1, sold: 0, active: true},
  {name: "VIP", description: "", event_id: 4, quantity: 50, start_t: "2019-09-05 03:00:00", end_t: "2019-11-01 11:00:00", price_cents: 20000, allotment: 1, sold: 0, active: true},
  {name: "Meia Entrada", description: "", event_id: 4, quantity: 100, start_t: "2019-09-01 03:00:00", end_t: "2019-10-16 02:59:00", price_cents: 2500, allotment: 1, sold: 0, active: true},
  {name: "Entrada", description: "", event_id: 5, quantity: 100, start_t: "2019-08-01 03:00:00", end_t: "2019-09-01 03:00:00", price_cents: 10000, allotment: 1, sold: 0, active: true},
  {name: "Entrada", description: "<div><!--block--><strong>2º Lote</strong></div>", event_id: 5, quantity: 100, start_t: "2019-01-01 02:00:00", end_t: "2019-09-09 18:00:00", price_cents: 12000, allotment: 2, sold: 0, active: true},
  {name: "Entrada Inteira", description: "", event_id: 6, quantity: 100, start_t: "2019-08-01 03:00:00", end_t: "2019-09-29 23:00:00", price_cents: 15000, allotment: 1, sold: 0, active: true},
  {name: "Meia Entrada", description: "", event_id: 6, quantity: 90, start_t: "2019-08-01 03:00:00", end_t: "2019-09-29 20:00:00", price_cents: 7500, allotment: 1, sold: 0, active: true},
  {name: "Entrada Franca", description: "", event_id: 7, quantity: 400, start_t: "2019-08-01 03:00:00", end_t: "2019-10-08 01:00:00", price_cents: 0, allotment: 1, sold: 0, active: true},
  {name: "Ingresso Único (Pré-Venda)", description: "", event_id: 8, quantity: 400, start_t: "2019-09-01 03:00:00", end_t: "2019-09-15 03:00:00", price_cents: 8000, allotment: 1, sold: 0, active: true},
  {name: "Ingresso Único", description: "", event_id: 9, quantity: 5000, start_t: "2019-07-01 03:00:00", end_t: "2019-09-28 23:00:00", price_cents: 10000, allotment: 1, sold: 0, active: true}
])
Address.create!([
  {name: nil, address: "Av. Belisário Leite de Andrade Neto", complement: "100", district: "Barra da Tijuca", city: "Rio de Janeiro", state: "RJ", zipcode: "22621-270", latitude: "-23.012511", longitude: "-43.307875", number: "300"},
  {name: "Maracanã", address: "Av. Pres. Castelo Branco", complement: "", district: "Maracanã", city: "Rio de Janeiro", state: "RJ", zipcode: "20271-130", latitude: "-22.9121089", longitude: "-43.2301558", number: "Portão 3"},
  {name: "Allianz Parque", address: "Av. Francisco Matarazzo", complement: "", district: "Água Branca", city: "São Paulo", state: " SP", zipcode: "05001-200", latitude: "-23.5274154", longitude: "-46.6785428", number: "1705"},
  {name: "Parque dos Atletas", address: "Av. Salvador Allende", complement: "", district: "Recreio dos Bandeirantes", city: "Rio de Janeiro", state: "RJ", zipcode: "22783-116", latitude: "-22.9806216", longitude: "-43.4068912", number: "6500"},
  {name: "Maracanã", address: "Av. Pres. Castelo Branco", complement: "", district: "Maracanã", city: "Rio de Janeiro", state: "RJ", zipcode: "20271-130", latitude: "-22.9121089", longitude: "-43.2301558", number: "Portão 3"},
  {name: "Allianz Parque", address: "Av. Francisco Matarazzo", complement: "", district: "Água Branca", city: "São Paulo", state: "SP", zipcode: "05001-200", latitude: "-23.5274154", longitude: "-46.6785428", number: "1705"},
  {name: "Estádio Mineirão", address: "Av. Antônio Abrahão Caram", complement: "", district: "São José", city: "Belo Horizonte", state: "MG", zipcode: "31275-000", latitude: "-19.865867", longitude: "-43.9711315", number: "1001"},
  {name: "Parque dos Atletas", address: "Av. Salvador Allende", complement: "", district: "Recreio dos Bandeirantes", city: "Rio de Janeiro", state: "RJ", zipcode: "22783-116", latitude: "-22.9806216", longitude: "-43.4068912", number: "6500"},
  {name: "Maracanã", address: "Av. Pres. Castelo Branco", complement: "", district: "Maracanã", city: "Rio de Janeiro", state: "RJ", zipcode: "20271-130", latitude: "-22.9121089", longitude: "-43.2301558", number: "Portão 3"},
  {name: "Parque dos Atletas", address: "Av. Salvador Allende", complement: "", district: "Recreio dos Bandeirantes", city: "Rio de Janeiro", state: "RJ", zipcode: "22783-116", latitude: "-22.9806216", longitude: "-43.4068912", number: "6500"}
])
